version: 2

sources:
  - name: oltp
    schema: oltp
    tables:
      - name: customers
        description: "Source table for customer information"

models:
  - name: stg_customers
    description: "Staging model for the customers table"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
      - name: first_name
        description: "Customer's first name"
      - name: last_name
        description: "Customer's last name"
      - name: gender
        description: "Gender of the customer"
      - name: birthdate
        description: "Date of birth"
      - name: email
        description: "Email address"
      - name: signup_date
        description: "Date when the customer signed up"