version: 2

sources:
  - name: oltp
    schema: oltp
    tables:
      - name: sales
        columns:
          - name: transaction_id
          - name: transaction_date
          - name: product_id
          - name: store_id
          - name: promotion_id
          - name: customer_id
          - name: quantity
          - name: unit_price
          - name: total_amount