version: 2

models:
  - name: dim_date
    description: "Calendar date dimension (one row per day)."
    columns:
      - name: date_sk
        description: "Surrogate key in YYYYMMDD integer format"
        tests: [not_null, unique]

      - name: full_date
        description: "The actual calendar date"
        tests: [not_null, unique]

      - name: year
      - name: quarter
      - name: month
      - name: month_name
      - name: day_of_month
      - name: day_of_year
      - name: week_of_year
      - name: weekday_iso
      - name: weekday_name
      - name: is_weekend