version: 2

models:
  - name: dim_stores
    description: "Store dimension with surrogate key"
    columns:
      - name: store_sk
        description: "Surrogate key for store"
        tests: [not_null, unique]
      - name: store_id
      - name: store_name
      - name: district
      - name: region
      - name: open_date
      - name: remodel_date
      - name: store_type