version: 2

models:
  - name: dim_products
    description: "Product dimension with surrogate key"
    columns:
      - name: product_sk
        description: "Surrogate key for product"
        tests: [not_null, unique]
      - name: product_id
        description: "Source product id from OLTP"
      - name: product_name
      - name: brand
      - name: subcategory
      - name: category
      - name: department
      - name: package_type
      - name: fat_content
      - name: diet_type