version: 2

sources:
  - name: oltp
    schema: oltp
    tables:
      - name: products
        description: "Source table for product information"

models:
  - name: stg_products
    description: "Staging model for the products table"
    columns:
      - name: product_id
        description: "Unique identifier for each product"
      - name: product_name
        description: "Name of the product"
      - name: brand
        description: "Brand associated with the product"
      - name: subcategory
        description: "Subcategory classification"
      - name: category
        description: "Category classification"
      - name: department
        description: "Higher-level department grouping"
      - name: package_type
        description: "Type of packaging (e.g. bottle, box)"
      - name: fat_content
        description: "Fat content label (e.g. low fat)"
      - name: diet_type
        description: "Diet classification (e.g. regular, diet)"
      - name: current_price
        description: "Current selling price of the product"
