version: 2

models:
  - name: dim_customers
    description: "Customer dimension table with surrogate key"
    columns:
      - name: customer_sk
        description: "Surrogate key for customer"
        tests:
          - not_null
          - unique

      - name: customer_id
        description: "Natural/business key for customer"
        tests:
          - not_null
          - unique

      - name: first_name
        description: "Customer first name"

      - name: last_name
        description: "Customer last name"

      - name: gender
        description: "Gender of the customer"

      - name: birthdate
        description: "Date of birth"

      - name: email
        description: "Email address"

      - name: signup_date
        description: "Date the customer signed up"