version: 2

models:
  - name: fct_sales
    description: "Transactional sales fact table"
    columns:
      - name: date_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_sk

      - name: customer_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_sk

      - name: product_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_sk

      - name: store_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_stores')
              field: store_sk

      - name: promotion_sk
        tests:
          - relationships:
              to: ref('dim_promotions')
              field: promotion_sk

      - name: quantity
      - name: unit_price
      - name: sales_amount

  - name: fct_promotion_eligibility
    description: "Factless fact table recording eligibility of promotions in each store on each date"
    columns:
      - name: date_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_sk

      - name: promotion_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_promotions')
              field: promotion_sk

      - name: store_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_stores')
              field: store_sk